export const APP_LOAD_BEGIN = "APP_LOAD_BEGIN";
export const APP_LOAD_SUCCESS = "APP_LOAD_SUCCESS";
export const APP_LOAD_FAILURE = "APP_LOAD_FAILURE";
export const APP_LOAD_DISMISS_ERROR = "APP_LOAD_DISMISS_ERROR";
